version: '3'
services:
  dataact-postgres:
    container_name: dataact-postgres
    image: postgres:9.4.7
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data_broker
    ports:
      - "8000:5432"

  dataact-broker:
    container_name: dataact-broker
    image: dataact-broker
    build:
      context: ./
    restart: always
    command: /bin/sh -c "cd ./dataactcore; sleep 10s; alembic upgrade head; top -b"
    ports:
      - "9000:9999"
    volumes:
      - ./:/data-act/backend
