version: '3'
services:
  dataact-postgres:
    container_name: dataact-postgres
    image: postgres:9.4.7
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: data_broker
    ports:
      - "8000:5432"

  dataact-broker:
    container_name: dataact-broker
    image: dataact-broker
    build:
      context: ./
      dockerfile: Dockerfile.broker
    restart: always
    ports:
      - "9000:8080"
    volumes:
      - ./:/workspace
